pymatbridge/matlab/util/json_v0.2.2/json/json_dump.m
pymatbridge/matlab/util/json_v0.2.2/json/json_load.m
pymatbridge/pymatbridge.py
pymatbridge/tests/test_array.py
pymatbridge/tests/test_get_variable.py
pymatbridge/tests/test_magic.py

Bottom line: array passing is 10X faster without using temporary files.
Uses base64 encoding to pass arrays between Matlab and Python using a similar method to `complex`.  For Python, numeric-type arrays are converted to float64 and then passed as a dictionary.  For Matlab, numeric arrays are converted to double and sent back as a structure.   
Also handles complex type arrays.  Side benefit: arrays are now returned as ndarrays. 
```python
With Base64:
In [3]: %time mlab.set_variable('ha', np.linspace(1.1, 2, 10000).reshape(100, 100))
CPU times: user 4.31 ms, sys: 1.61 ms, total: 5.92 ms
Wall time: 163 ms
Out[3]: {'success': 'true', 'result': 1, 'message': 'Successfully completed request'}
In [4]: %time b = mlab.get_variable('ha')
CPU times: user 3.93 ms, sys: 1.09 ms, total: 5.02 ms
Wall …
```

Efficient Array Passing

---

.travis.yml
README.md

@dhermes - how does this look to you? 
If you think this is ready to go, I will merge it. 
Then, we can close #113

Dhermes travis pypi

---

pymatbridge/pymatbridge.py

Older versions of NumPy don't supply the tobytes method. However, it is stated in the NumPy release notes for 1.9.0 ( http://docs.scipy.org/doc/numpy/release.html ) ( https://github.com/numpy/numpy/blob/master/doc/release/1.9.0-notes.rst ) that this behaves the same as tostring. So, this workaround tries to use tostring if tobytes fails.

Backward compatible handling of NumPy arrays

---

pymatbridge/matlab_magic.py

This PR is to address arokem#117. It ensures that MatlabInterperterError is re-raised so the user can get some feedback as to what caused the error if there was one. If anyone wants to improve on it, feel free.

Forward MatlabInterperterError to the user

---

pymatbridge/pymatbridge.py

You're already capturing `stdout` using `diary`, the test suite still passes, and we get no double print. :smile:

Pipe stdout to subprocess.PIPE

---

pymatbridge/matlab/util/pymat_feval.m
pymatbridge/matlab/util/run_dot_m.m
pymatbridge/pymatbridge.py

I also changed the semantics of `run_func` a bit.  You can now call built-in functions and pass a single argument that is not a dictionary.  Here was my test case:
```python
In [2]: from pymatbridge import Matlab
In [3]: m = Matlab();m.start()
Starting MATLAB on ZMQ socket ipc:///tmp/pymatbridge
Send 'exit' command to kill the server
.....MATLAB started and connected!
Out[3]: True
In [4]: res  = m.run_func('svd', np.array([[1,2],[1,3]]), nargout=3)
In [5]: U, S, V = res['result']
In [6]: U, S, V
Out[6]: 
(array([[-0.57604844, -0.81741556],
[-0.81741556,  0.57604844]]), array([[ 3.86432845,  0.        ],
[ 0.        ,  0.25877718]]), array([[-0.36059668, -0.93272184],
[-0.93272184,  0.36059668]]))
```
This definitely warrants new test cases and some thought about to handle an array (list) …

Update handling of nargout

---

pymatbridge/matlab/util/run_dot_m.m
pymatbridge/pymatbridge.py
pymatbridge/tests/test_run_code.py

Add explicit tests for `nargout=1` and `nargout=0` in `run_func`.
Add support for tuples and and cell-like objects in `run_func`.
Beef up some documentation.

More nargout tests and handle tuple arguments

---

.travis.yml

As a result of some earlier refactoring, the Python 3.4 build is now cooperating.

Add Python 3.4 to Travis Build

---

pymatbridge/matlab/util/json_v0.2.2/json/json_dump.m
pymatbridge/pymatbridge.py
pymatbridge/tests/test_functions.py
pymatbridge/tests/test_run_code.py

This implements #63.  The only change to existing behaviour is to the interface to `run_func`.

Add function maker

---

pymatbridge/matlab_magic.py

Certainly, we don't need to mention "R" in our docs :-)

RF: We probably don't need this variable.

---

pymatbridge/pymatbridge.py

Prior to this change, trying to run `m.version()` without calling `m.start()` gave this unhelpful message:
```python
/home/silvester/workspace/python-matlab-bridge/pymatbridge/pymatbridge.py in _response(self, **kwargs)
221     def _response(self, **kwargs):
222         req = json.dumps(kwargs, cls=PymatEncoder)
--> 223         self.socket.send_string(req)
224         resp = self.socket.recv_string()
225         return resp
AttributeError: 'NoneType' object has no attribute 'send_string'
```
Also allows you to use `m = Matlab().start()`

Start the session if you try and run code

---

.travis.yml
pymatbridge/publish.py
pymatbridge/tests/test_publish.py

Fixes test breakage on current master, due to the move to IPython 3.0

Publish matlab kernel

---

messenger/mexw64/README.md

This fixes #69 and documents what was done in #161

Add build instructions for messenger.mexw64

---

README.md

Thanks to @kjaquier for proposing this on #177

DOC: Small update in the installation instructions.

---

pymatbridge/matlab/matlabserver.m
pymatbridge/pymatbridge.py

Fixes #168, addresses #164.
I could not find a way to reliably interrupt the Matlab process and recover from it, but at least now Ctrl+C results in a clean shutdown of the Matlab process.

Fix matlabserver shutdown behavior

---

pymatbridge/pymatbridge.py

Current directory was not respected on Windows when `-automation` flag is used, as previously [reported here](http://www.mathworks.com/matlabcentral/answers/58372-can-t-change-startup-directory-when-calling-matlab-with-automation-from-command-line). Changing the directory therefore allows for more consistent behavior across different platforms.
I've also suppressed verbose startup output by suffixing commands with semicolon.

Respect current directory when starting MATLAB on Windows

---

pymatbridge/pymatbridge.py

RF: Create a random socket location for every instance.

---

pymatbridge/matlab/util/pymat_eval.m
pymatbridge/tests/test_run_code.py
pymatbridge/tests/test_stack_trace.m

If an error happens while executing the code, grab the stack trace and include it in a new `stack` field on the response. (See the test for what this field looks like).
Unfortunately the code is a little awkward because I wanted the output to be the same in both MATLAB and Octave.
This is relevant for #160, although it doesn't quite solve it. It shouldn't be hard to add some code to the matlab magic that uses the `stack` field and builds a nice error message out of it like MATLAB does. I don't really use ipython so I'm not really the best person to write & test this.

Include the stack trace in the response on error.

---

pymatbridge/pymatbridge.py

In a scenario where PyMatBridge is used with other Python ZMQ sessions, it would make sense for the JSON encoder and decoder to be compatible, so that they can be used to send variables over a channel from one Python program to another. 
Currently, what Python encodes, Matlab can decode and vice versa. But what Python encodes cannot be decoded by itself. This pull requests addresses this issue and is also backward compatible and doesn't break any current usage. I only found this non-reversibility bug in ndarrays and this fixes it.

Made json encode/decode reversible

---

pymatbridge/matlab/util/pymat_eval.m

If a user is editing a file, the changes are not reflected in the pymatbridge Matlab session.  This forces a behavior consistent with the Matlab command window.
See https://github.com/Calysto/matlab_kernel/issues/14#issuecomment-124966296.

Force a rehash of user functions

---

.travis.yml
pymatbridge/publish.py

Same as #213, but updated with recent master

Update with nbformat

---

pymatbridge/matlab_magic.py
pymatbridge/tests/test_magic.py

Should possibly help address some of the issues mentioned in #223

NF: Allow passing of all kwargs to the Matlab/Octave init in the magic.

---

pymatbridge/matlab/util/pymat_eval.m

Fixes #228. This seems to work for my use-cases and passes the tests, but let me know if there are any edge-cases that breaks because of this.

Always make cell array of function arguments

---

pymatbridge/__init__.py
pymatbridge/pymatbridge.py
setup.py

The main feature of this pull request is that it changes the messenger architecture to be detected at runtime instead of at setup. This makes it easier to package the project and makes it possible to remove some of the hacks from `setup.py`. It also fixes an issue with some users not having the correct messenger files installed (see e.g. https://github.com/arokem/python-matlab-bridge/issues/220#issuecomment-201360155).

Clean up messenger handling
